Lua doc comment improvements for better API reference generation (#185)
Improvements to the Lua doc comments that allows improved 
generation of the Lua API reference using the gendocs plugin.

diff --git a/scripts/run-local b/scripts/run-local
--- a/scripts/run-local
+++ b/scripts/run-local
@@ -27,8 +27,12 @@ while [[ "$#" -gt 0 ]]; do
     option_global=on
     ;;
     -*)
-    echo "error: unknown option \"$1\""
-    exit 1
+    if [ "${#pargs[@]}" = "0" ]; then
+      echo "error: unknown option \"$1\""
+      exit 1
+    else
+      pargs+=("$1")
+    fi
     ;;
     *)
     pargs+=("$1")
